import enum

from ._libretro import *


class Rotation(enum.IntEnum):
    NONE = 0
    _90 = 1
    _180 = 2
    _270 = 3


class PixelFormat(enum.IntEnum):
    RGB1555 = RETRO_PIXEL_FORMAT_0RGB1555
    XRGB8888 = RETRO_PIXEL_FORMAT_XRGB8888
    RGB565 = RETRO_PIXEL_FORMAT_RGB565


class Region(enum.IntEnum):
    NTSC = RETRO_REGION_NTSC
    PAL = RETRO_REGION_PAL


class Language(enum.IntEnum):
    English = RETRO_LANGUAGE_ENGLISH
    Japanese = RETRO_LANGUAGE_JAPANESE
    French = RETRO_LANGUAGE_FRENCH
    Spanish = RETRO_LANGUAGE_SPANISH
    German = RETRO_LANGUAGE_GERMAN
    Italian = RETRO_LANGUAGE_ITALIAN
    Dutch = RETRO_LANGUAGE_DUTCH
    PortugueseBrazil = RETRO_LANGUAGE_PORTUGUESE_BRAZIL
    PortuguesePortugal = RETRO_LANGUAGE_PORTUGUESE_PORTUGAL
    Russian = RETRO_LANGUAGE_RUSSIAN
    Korean = RETRO_LANGUAGE_KOREAN
    ChineseTraditional = RETRO_LANGUAGE_CHINESE_TRADITIONAL
    ChineseSimplified = RETRO_LANGUAGE_CHINESE_SIMPLIFIED
    Esperanto = RETRO_LANGUAGE_ESPERANTO
    Polish = RETRO_LANGUAGE_POLISH
    Vietnamese = RETRO_LANGUAGE_VIETNAMESE
    Arabic = RETRO_LANGUAGE_ARABIC
    Greek = RETRO_LANGUAGE_GREEK
    Turkish = RETRO_LANGUAGE_TURKISH
    Slovak = RETRO_LANGUAGE_SLOVAK
    Persian = RETRO_LANGUAGE_PERSIAN
    Hebrew = RETRO_LANGUAGE_HEBREW
    Asturian = RETRO_LANGUAGE_ASTURIAN
    Finnish = RETRO_LANGUAGE_FINNISH
    Indonesian = RETRO_LANGUAGE_INDONESIAN
    Swedish = RETRO_LANGUAGE_SWEDISH
    Ukrainian = RETRO_LANGUAGE_UKRAINIAN
    Czech = RETRO_LANGUAGE_CZECH
    CatalanValencia = RETRO_LANGUAGE_CATALAN_VALENCIA
    Catalan = RETRO_LANGUAGE_CATALAN
    BritishEnglish = RETRO_LANGUAGE_BRITISH_ENGLISH
    Hungarian = RETRO_LANGUAGE_HUNGARIAN
    Belarusian = RETRO_LANGUAGE_BELARUSIAN


