from enum import IntFlag, CONFORM

from ..h import *

class AvEnableFlags(IntFlag, boundary=CONFORM):
    VIDEO = RETRO_AV_ENABLE_VIDEO
    AUDIO = RETRO_AV_ENABLE_AUDIO
    FAST_SAVESTATES = RETRO_AV_ENABLE_FAST_SAVESTATES
    HARD_DISABLE_AUDIO = RETRO_AV_ENABLE_HARD_DISABLE_AUDIO
