from enum import IntFlag, IntEnum

from ..h import *


class SerializationQuirks(IntFlag):
    INCOMPLETE = RETRO_SERIALIZATION_QUIRK_INCOMPLETE
    MUST_INITIALIZE = RETRO_SERIALIZATION_QUIRK_MUST_INITIALIZE
    CORE_VARIABLE_SIZE = RETRO_SERIALIZATION_QUIRK_CORE_VARIABLE_SIZE
    FRONTEND_VARIABLE_SIZE = RETRO_SERIALIZATION_QUIRK_FRONT_VARIABLE_SIZE
    SINGLE_SESSION = RETRO_SERIALIZATION_QUIRK_SINGLE_SESSION
    ENDIAN_DEPENDENT = RETRO_SERIALIZATION_QUIRK_ENDIAN_DEPENDENT
    PLATFORM_DEPENDENT = RETRO_SERIALIZATION_QUIRK_PLATFORM_DEPENDENT

    ALL = INCOMPLETE | MUST_INITIALIZE | CORE_VARIABLE_SIZE | FRONTEND_VARIABLE_SIZE | SINGLE_SESSION | ENDIAN_DEPENDENT | PLATFORM_DEPENDENT


class SavestateContext(IntEnum):
    NORMAL = RETRO_SAVESTATE_CONTEXT_NORMAL
    RUNAHEAD_SAME_INSTANCE = RETRO_SAVESTATE_CONTEXT_RUNAHEAD_SAME_INSTANCE
    RUNAHEAD_SAME_BINARY = RETRO_SAVESTATE_CONTEXT_RUNAHEAD_SAME_BINARY
    ROLLBACK_NETPLAY = RETRO_SAVESTATE_CONTEXT_ROLLBACK_NETPLAY

    def __init__(self, value: int):
        self._type_ = 'i'


__all__ = [
    'SerializationQuirks',
    'SavestateContext',
]
