from abc import abstractmethod
from ctypes import c_void_p, c_bool, c_uint, CFUNCTYPE
from enum import IntEnum, unique
from typing import Protocol

from ...h import *


@unique
class EnvironmentCall(IntEnum):
    SET_ROTATION = RETRO_ENVIRONMENT_SET_ROTATION
    GET_OVERSCAN = RETRO_ENVIRONMENT_GET_OVERSCAN
    GET_CAN_DUPE = RETRO_ENVIRONMENT_GET_CAN_DUPE
    SET_MESSAGE = RETRO_ENVIRONMENT_SET_MESSAGE
    SHUTDOWN = RETRO_ENVIRONMENT_SHUTDOWN
    SET_PERFORMANCE_LEVEL = RETRO_ENVIRONMENT_SET_PERFORMANCE_LEVEL
    GET_SYSTEM_DIRECTORY = RETRO_ENVIRONMENT_GET_SYSTEM_DIRECTORY
    SET_PIXEL_FORMAT = RETRO_ENVIRONMENT_SET_PIXEL_FORMAT
    SET_INPUT_DESCRIPTORS = RETRO_ENVIRONMENT_SET_INPUT_DESCRIPTORS
    SET_KEYBOARD_CALLBACK = RETRO_ENVIRONMENT_SET_KEYBOARD_CALLBACK
    SET_DISK_CONTROL_INTERFACE = RETRO_ENVIRONMENT_SET_DISK_CONTROL_INTERFACE
    SET_HW_RENDER = RETRO_ENVIRONMENT_SET_HW_RENDER
    SET_HW_RENDER_EXPERIMENTAL = RETRO_ENVIRONMENT_SET_HW_RENDER | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_VARIABLE = RETRO_ENVIRONMENT_GET_VARIABLE
    SET_VARIABLES = RETRO_ENVIRONMENT_SET_VARIABLES
    GET_VARIABLE_UPDATE = RETRO_ENVIRONMENT_GET_VARIABLE_UPDATE
    SET_SUPPORT_NO_GAME = RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME
    GET_LIBRETRO_PATH = RETRO_ENVIRONMENT_GET_LIBRETRO_PATH
    SET_FRAME_TIME_CALLBACK = RETRO_ENVIRONMENT_SET_FRAME_TIME_CALLBACK
    SET_AUDIO_CALLBACK = RETRO_ENVIRONMENT_SET_AUDIO_CALLBACK
    GET_RUMBLE_INTERFACE = RETRO_ENVIRONMENT_GET_RUMBLE_INTERFACE
    GET_INPUT_DEVICE_CAPABILITIES = RETRO_ENVIRONMENT_GET_INPUT_DEVICE_CAPABILITIES
    GET_SENSOR_INTERFACE = RETRO_ENVIRONMENT_GET_SENSOR_INTERFACE
    GET_CAMERA_INTERFACE = RETRO_ENVIRONMENT_GET_CAMERA_INTERFACE
    GET_LOG_INTERFACE = RETRO_ENVIRONMENT_GET_LOG_INTERFACE
    GET_PERF_INTERFACE = RETRO_ENVIRONMENT_GET_PERF_INTERFACE
    GET_LOCATION_INTERFACE = RETRO_ENVIRONMENT_GET_LOCATION_INTERFACE
    GET_CORE_ASSETS_DIRECTORY = RETRO_ENVIRONMENT_GET_CORE_ASSETS_DIRECTORY
    GET_SAVE_DIRECTORY = RETRO_ENVIRONMENT_GET_SAVE_DIRECTORY
    SET_SYSTEM_AV_INFO = RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO
    SET_PROC_ADDRESS_CALLBACK = RETRO_ENVIRONMENT_SET_PROC_ADDRESS_CALLBACK
    SET_SUBSYSTEM_INFO = RETRO_ENVIRONMENT_SET_SUBSYSTEM_INFO
    SET_CONTROLLER_INFO = RETRO_ENVIRONMENT_SET_CONTROLLER_INFO
    SET_MEMORY_MAPS = RETRO_ENVIRONMENT_SET_MEMORY_MAPS
    SET_GEOMETRY = RETRO_ENVIRONMENT_SET_GEOMETRY
    GET_USERNAME = RETRO_ENVIRONMENT_GET_USERNAME
    GET_LANGUAGE = RETRO_ENVIRONMENT_GET_LANGUAGE
    GET_CURRENT_SOFTWARE_FRAMEBUFFER = RETRO_ENVIRONMENT_GET_CURRENT_SOFTWARE_FRAMEBUFFER
    GET_HW_RENDER_INTERFACE = RETRO_ENVIRONMENT_GET_HW_RENDER_INTERFACE
    SET_SUPPORT_ACHIEVEMENTS = RETRO_ENVIRONMENT_SET_SUPPORT_ACHIEVEMENTS
    SET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE = RETRO_ENVIRONMENT_SET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE
    SET_SERIALIZATION_QUIRKS = RETRO_ENVIRONMENT_SET_SERIALIZATION_QUIRKS
    SET_HW_SHARED_CONTEXT = RETRO_ENVIRONMENT_SET_HW_SHARED_CONTEXT
    GET_VFS_INTERFACE = RETRO_ENVIRONMENT_GET_VFS_INTERFACE
    GET_LED_INTERFACE = RETRO_ENVIRONMENT_GET_LED_INTERFACE
    GET_AUDIO_VIDEO_ENABLE = RETRO_ENVIRONMENT_GET_AUDIO_VIDEO_ENABLE
    GET_MIDI_INTERFACE = RETRO_ENVIRONMENT_GET_MIDI_INTERFACE
    GET_FASTFORWARDING = RETRO_ENVIRONMENT_GET_FASTFORWARDING
    GET_TARGET_REFRESH_RATE = RETRO_ENVIRONMENT_GET_TARGET_REFRESH_RATE
    GET_INPUT_BITMASKS = RETRO_ENVIRONMENT_GET_INPUT_BITMASKS
    GET_CORE_OPTIONS_VERSION = RETRO_ENVIRONMENT_GET_CORE_OPTIONS_VERSION
    SET_CORE_OPTIONS = RETRO_ENVIRONMENT_SET_CORE_OPTIONS
    SET_CORE_OPTIONS_INTL = RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL
    SET_CORE_OPTIONS_DISPLAY = RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY
    GET_PREFERRED_HW_RENDER = RETRO_ENVIRONMENT_GET_PREFERRED_HW_RENDER
    GET_DISK_CONTROL_INTERFACE_VERSION = RETRO_ENVIRONMENT_GET_DISK_CONTROL_INTERFACE_VERSION
    SET_DISK_CONTROL_EXT_INTERFACE = RETRO_ENVIRONMENT_SET_DISK_CONTROL_EXT_INTERFACE
    GET_MESSAGE_INTERFACE_VERSION = RETRO_ENVIRONMENT_GET_MESSAGE_INTERFACE_VERSION
    SET_MESSAGE_EXT = RETRO_ENVIRONMENT_SET_MESSAGE_EXT
    GET_INPUT_MAX_USERS = RETRO_ENVIRONMENT_GET_INPUT_MAX_USERS
    SET_AUDIO_BUFFER_STATUS_CALLBACK = RETRO_ENVIRONMENT_SET_AUDIO_BUFFER_STATUS_CALLBACK
    SET_MINIMUM_AUDIO_LATENCY = RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY
    SET_FASTFORWARDING_OVERRIDE = RETRO_ENVIRONMENT_SET_FASTFORWARDING_OVERRIDE
    SET_CONTENT_INFO_OVERRIDE = RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE
    GET_GAME_INFO_EXT = RETRO_ENVIRONMENT_GET_GAME_INFO_EXT
    SET_CORE_OPTIONS_V2 = RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2
    SET_CORE_OPTIONS_V2_INTL = RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL
    SET_CORE_OPTIONS_UPDATE_DISPLAY_CALLBACK = RETRO_ENVIRONMENT_SET_CORE_OPTIONS_UPDATE_DISPLAY_CALLBACK
    SET_VARIABLE = RETRO_ENVIRONMENT_SET_VARIABLE
    GET_THROTTLE_STATE = RETRO_ENVIRONMENT_GET_THROTTLE_STATE
    GET_SAVESTATE_CONTEXT = RETRO_ENVIRONMENT_GET_SAVESTATE_CONTEXT
    GET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE_SUPPORT = RETRO_ENVIRONMENT_GET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE_SUPPORT
    GET_JIT_CAPABLE = RETRO_ENVIRONMENT_GET_JIT_CAPABLE
    GET_MICROPHONE_INTERFACE = RETRO_ENVIRONMENT_GET_MICROPHONE_INTERFACE
    SET_NETPACKET_INTERFACE = RETRO_ENVIRONMENT_SET_NETPACKET_INTERFACE
    GET_DEVICE_POWER = RETRO_ENVIRONMENT_GET_DEVICE_POWER
    GET_PLAYLIST_DIRECTORY = RETRO_ENVIRONMENT_GET_PLAYLIST_DIRECTORY

    def __init__(self, value: int):
        self._type_ = 'I'


retro_environment_t = CFUNCTYPE(c_bool, c_uint, c_void_p)


class EnvironmentCallback(Protocol):
    @abstractmethod
    def environment(self, cmd: int, data: c_void_p) -> bool: ...


__all__ = [
    'EnvironmentCall',
    'retro_environment_t',
    'EnvironmentCallback',
]
