name: Validate URLs

on:
  push:
    branches:
      - main
    paths: ["**.md", "**.yaml", "**.yml", "**.py", "**.pyi", "**.rst", "**.txt", "**.toml"]
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight UTC

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate URLs
        uses: urlstechie/urlchecker-action@b643b43e2ac605e1475331c7b67247d242b7dce4 # 0.0.34
        with:
          file_types: .md,.yaml,.yml,.py,.pyi,.rst,.txt,.toml
          print_all: false
          timeout: 10
          retry_count: 3