name: Check & Test

on:
  workflow_dispatch:
    # Allow manual triggering of this workflow
    inputs:
      run-id:
        type: string
        description: "Workflow run ID"
        required: false
      dry-run:
        type: boolean
        description: "Skip release steps"
        required: false
        default: true
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  check:
    name: Run Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Test against multiple Python versions to ensure compatibility
        python-version: ["3.12", "3.13", "3.14"]
    steps:
      - name: Check Out Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Just
        uses: extractions/setup-just@c26183993cea0054160ffaaa55fab2cad53c12fc # v3.1.0

      - name: Install Build Requirements
        run: sudo apt-get install libx11-dev

      - name: Install Python and Dependencies
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          pip-install: .[all]

      - name: Check Types
        run: just pyright

      - name: Check Style
        run: just black-check isort-check

      - name: Build Package
        run: just build
        # Uses the "build" recipe from the justfile

      - name: Upload Build
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ matrix.python-version == '3.14' }}
        # Only upload artifacts for the latest Python version,
        # since the package should be the same for all versions
        with:
          archive: false
          path: dist/libretro_py-*.whl
          if-no-files-found: error
